import Head from "next/head";
import {
  Stack,
  Center,
  Container,
  Heading,
  Button,
  HStack,
  Image,
  Box,
  Text,
  Divider,
} from "@chakra-ui/react";
import NextLink from "next/link";

export default function Example() {
  return (
    <>
      <Head>
        <title>Promptomize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="100%" h="100vh" mt="30px">
        <Box>
          <Text borderBottom="2px" borderColor="#51da4c" fontSize="25px">
            It Makes a Big Difference
          </Text>
        </Box>
        <Stack direction="row" gap="100px" pt="100">
          <Stack direction="column" gap="20px" m="0">
            <Text mt="0" fontSize="20px" w="50%">
              GPT-4 is more creative and collaborative than ever before. It can
              generate, edit, and iterate with users on creative and technical
              writing tasks, such as composing songs, writing screenplays, or
              learning a users writing style.
            </Text>
            <Button
              bg="transparent"
              color="#51da4c"
              borderColor="black"
              size="md"
              borderRadius="0"
              border="2px"
              fontWeight={400}
              w="30%"
              _hover={{
                background: "black",
                color: "#51da4c",
              }}
            >
              <NextLink href="/magic">
                {" "}
                <Text color="black">Promptomize</Text>{" "}
              </NextLink>
            </Button>
          </Stack>

          <Box w="90%" border="2px" borderColor="#51da4c" p="15px">
            <Box borderBottom="2px" mb="20px" borderColor="#51da4c">
              <Heading fontSize="20px" mb="25px">
                Input
              </Heading>
              <Text mb="25px">How can I write better content on Twitter?</Text>
            </Box>
            <Box>
              <Heading fontSize="20px"> Output</Heading>
              {/* //Type animation */}
            </Box>
          </Box>
        </Stack>
      </Container>
    </>
  );
}
