import Head from "next/head";
import {
  Stack,
  Center,
  Container,
  Heading,
  Button,
  HStack,
  Image,
  Box,
  Text,
  Divider,
} from "@chakra-ui/react";
import Example from "@/components/Example";
import Hero from "@/components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Promptomize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Container maxW="100%" backgroundColor="white">
        <Example />
      </Container>
    </>
  );
}
