import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import {
  VStack,
  Center,
  Text,
  Heading,
  Button,
  Input,
  FormControl,
  Box,
  Container,
  HStack,
} from "@chakra-ui/react";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [learn, setLearn] = useState("");
  const [data, setData] = useState("");

  const handleInputFormChange = (event: any) => {
    setLearn(event.target.value);
  };

  const handleSubmit = async (event: { preventDefault: () => void }) => {
    event.preventDefault();

    try {
      setIsLoading(true);

      const response = await axios.post("/api/generate-text", {
        prompt: learn,
      });

      setData(response.data);
    } catch (error) {
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Head>
        <title>Promptomize</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="100%" bg="black">
        <Center>
          <VStack w="5xl" h="100vh" gap="50px">
            <Heading fontSize="50px" mt="10" color="#51da4c">
              It's time to super charge your prompt!
            </Heading>
            <HStack w="100%">
              <FormControl id="prompt" fontSize={"2xl"}>
                <Box>
                  <Input
                    bg="transparent"
                    color="#51da4c"
                    borderRadius="0"
                    border="2px"
                    p="9px"
                    placeholder="How do I write better content on Twitter?"
                    size="lg"
                    variant="unstyled"
                    autoComplete="off"
                    onChange={handleInputFormChange}
                    value={learn}
                  />
                </Box>
              </FormControl>
              <Button
                bg="transparent"
                color="#51da4c"
                size="lg"
                w="30%"
                borderRadius="0"
                border="2px"
                p="20px"
                onClick={handleSubmit}
                isLoading={isLoading}
                _hover={{
                  background: "#51da4c",
                  color: "black",
                }}
              >
                {" "}
                Promptimize
              </Button>
            </HStack>
            <Box padding="6" bg="transparent" borderRadius="lg">
              <Text fontSize="20px" whiteSpace="pre-wrap">
                {data}
              </Text>
            </Box>
          </VStack>
        </Center>
      </Container>
    </>
  );
}

import type { NextApiRequest, NextApiResponse } from "next";
// const { Configuration, OpenAIApi } = require("openai");

// type Data = {
//   name: string;
//   message?: string;
//   error: string;
// };

// export default async function handler(
//   req: NextApiRequest,
//   res: NextApiResponse<Data>
// ) {
//   try {
//     const prompt = req.body.prompt;

//     const configuration = new Configuration({
//       apiKey: "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",
//     });
//     const openai = new OpenAIApi(configuration);

//     const charles = async () => {
//       console.log("bi");
//       const completion = await openai.createCompletion({
//         model: "text-davinci-003",
//         prompt: prompt,
//         maxTokens: 2048,
//       });
//       console.log(completion.data.choices[0].text);
//       return completion.data.choices[0].text;
//     };

//     const result = await charles();
//     res.status(200).json(result);
//   } catch (error) {
//     console.error(error);
//     if (error.response && error.response.status) {
//       res.status(error.response.status).json({ message: error.message });
//     } else if (error.request && error.request.status) {
//       res.status(error.request.status).json({ message: error.message });
//     } else {
//       res.status(500).json({ message: error.message });
//     }
//   }
// }
